language: node_js
node_js:
- node
services:
- mongodb
env:
 global:
   - NODE_ENV=test
   - CXX=g++-4.8
   - secure: UZE77jQ01FaR9egfPAizo+1kdnUXLla3quZInCT3YWUJmI48qAVAcA9EVms7dikYPhriuT1Qtje1SOeEzZnjaDAISmjpkYTw5dT3ZZQ11pdGWJE16SExi13cQtATq4MZf7DalzqfX81c7Nh212eq/mKDzC1tlgHeF3k4nlMRgdSFm3dc2bojfv+B3/It0TpQRO0fyeGhTW1PKILA8xWS/2MrGGy0epJEBxVxaI9CLK3fW7UmPis2dpdCRetMOg/SaJjtwc/7jzMZ2SPs4b0+KRNrCVfI9lLxFcIPd0nn/f4Dd8XX+X4YkxS5UwjR8AF30OZ19ExLKQfHv7zT5LjVvl7SAlRwioPA6r9GYN4V2atFFlD2clPKysFJlawXvQRAqYYfPXDOYFXaMfZAXy8HNcU9wNsuBfqcQFEJ1VEMGp/GntUqjhUjw4kzmdx/2QN7Fa4Nyu7Mr2jS7pmj4befVqzdzIeyBfbiLNIaz2e+jYX6xOxxc0xUrWLC3LajTr599qXO1TAZ+iQb820scclREchvd2xQ1j+2K0Bd+WbcooGMG02+VO1GoJABR18Vor2BCPU/zr9fQ2+Dxj2Z9kpSiDFM5E0V75KvkdUj/FrIZBXZFufTlzwyGg3r0/ZrY4RqfuEaXI/3Ui8CLu8CaLDqwhvLIpoSUgI/gedPZt5nqRg=
   - secure: KUvCJb/xqiiefX+9RmTFQeIFs7y70e4UINizrdMmOhvesiY+Zhr8Dcz1+kV5dvmEXxE0HwU+h5QWiIyGc2BNHJJ78C6tg2KfCWsOqkMKuzUyRug7L5SmOGejAQvCmCFgatgFKEzoC+qk0FMFM3KkrZMEj63tMKvHhnqpEWp4rXHIUbqvmUCi6GFFZxMUtx6JG3dOCji9lNoH2hyPo+ilNotgMeA1cZc0OiqAz87xfyee9N6TgIBHGmKDGNvvjCTyyWBp+/beNF9EP8SA57YfFvZmw5CH9JfVOiP4TR4fpBUzdzQrpAPbh1eXcksSGtrBrBFpQTJU8Hf+bDQHDaDp7XM9I+JeC11o1o6fe7IeFSOQDHVnYpYXah3I3cUM3oG7UV3Jr6GCl3c5gh+kB56YFb78fgoTMsXKUMbfiUMG+S2HM98U88fDoW20u7bLwFs5GEG3JQz/UeUGlVe5cJWa7x9WsMzfjVGQwK2qPah9hrU8T6aKkRXQQJjqzrs7/rbWMi3Fq4SZSRT0tmGzBDsiIGDwRu7yI0F4knAGIf8Y2f1isXfdg9flasf7Ed3ebsV75UFoztcJzoM+UqVmVoclYg8QKo5bfNoAfgSiC4lQMF4+HTUyTr/Ld2GTPx3EnhlbjnOoVspW7fO1G+8qWTg1+8RsoohUIVo5qsOK6y/gAng=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
- g++-4.8